variables:
  AUDIT_AWS_ELB_ALERT_LIST:
    description: "Which alerts would you like to check for? (Default is all ELB alerts)"
    required: true
    type: array
    default:
      - elb-old-ssl-policy
  AUDIT_AWS_ELB_ALERT_RECIPIENT:
    description: "Enter the email address(es) that will receive notifications. If more than one, separate each with a comma."
    required: true
    type: string
    default:
  AUDIT_AWS_ELB_ALERT_NO_OWNER_RECIPIENT:
    description: "Enter the email address(es) that will receive notifications for objects with no owner tag (Optional, only if owner tag is enabled)."
    required: false
    type: string
    default:
  AUDIT_AWS_ELB_ALLOW_EMPTY:
    description: "Would you like to receive empty reports? Options - true / false. Default is true."
    required: true
    type: string
    default: true
  AUDIT_AWS_ELB_SEND_ON:
    description: "Send reports always or only when there is a change? Options - always / change. Default is always."
    required: true
    type: string
    default: "always"
  AUDIT_AWS_ELB_OWNER_TAG:
    description: "Enter an AWS tag whose value is an email address of owner of the ELB object. (Optional)"
    required: false
    type: string
    default: "NOT_A_TAG"
  AUDIT_AWS_ELB_FULL_JSON_REPORT:
    description: "Would you like to receive the full JSON report? Options - notify / nothing. Default is notify."
    required: true
    type: string
    default: "notify"
  AUDIT_AWS_ELB_OWNERS_HTML_REPORT:
    description: "Would you like to receive the AWS owner tag report? Options - notify / nothing. Default is no / nothing."
    required: true
    type: string
    default: "nothing"  
  AUDIT_AWS_ELB_ROLLUP_REPORT:
    description: "Would you like to receive a Summary ELB report? Options - notify / nothing. Default is no / nothing."
    required: true
    type: string
    default: "nothing"  
  AUDIT_AWS_ELB_DEBUG_REPORT:
    description: "Would you like to receive an ELB debug report? Options - notify / nothing. Default is no / nothing."
    required: true
    type: string
    default: "nothing"  
  AUDIT_AWS_ELB_REGIONS:
    description: "List of AWS regions to check. Default is us-east-1,us-west-1,us-west-2,eu-west-1."
    required: true
    type: array
    default:
        - us-east-1
        - us-west-1
        - us-west-2
#       - ap-south-1
#       - ap-northeast-1
#       - ap-northeast-2
#       - ap-southeast-1
#       - ap-southeast-2
#       - eu-central-1
       - eu-west-1
#       - sa-east-1

#      - elb-inventory
#      - elb-current-ssl-policy
